default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: alpha_blog_development

test:
  <<: *default
  database: alpha_blog_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
